apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: gather-cronjob
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: gather-container
              image: chtedock/gather-script
          restartPolicy: Never
